version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Create virtualenv
          command: python -m venv venv
      - run:
          name: Active virtualenv
          command: . venv/bin/activate
